APP: 'employee-system'
NAME: 'es-salary'
MICROSERVICE: 'salary'
DOCKER_APP_IMAGE: 'public.ecr.aws/j9k0i2s2/dev-or-employee-system:salary-main-test'
NAMESPACE: 'dev'
K8S_REPLICAS: '1'
K8S_MAX_UNAVAIL: '1'
K8S_MAX_SURGE: '1'
K8S_REQ_MEM: '64Mi'
K8S_REQ_CPU: '100m'
K8S_LIMIT_MEM: '128Mi'
K8S_LIMIT_CPU: '150m'
AUTOSCALE_MIN_REPLICA: '2'
AUTOSCALE_MAX_REPLICA: '4'
AUTOSCALE_CPU_PERCENTAGE: '50'